blank_issues_enabled: false
contact_links:
  - name: ğŸ‘ Community Issues & Discussions (Start Here)
    url: https://github.com/pikapkg/snowpack/discussions/new?category_id=16417352
    about: Say hi, get help, suggest a feature
